//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscipEntities : DbContext
    {
        public DiscipEntities()
            : base("name=DiscipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
       private static DiscipEntities context;
      public static  DiscipEntities GetContext()
        {
            if (context == null)
            {
                context = new DiscipEntities();
            }
            return context;
        }
        public virtual DbSet<Table_1> Table_1 { get; set; }
    }
}
