//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string SecondName { get; set; }
        public int NumberZach { get; set; }
        public string WhereLeav { get; set; }
        public string NumberGroup { get; set; }
        public Nullable<int> PredmetA { get; set; }
        public Nullable<int> PredmetB { get; set; }
        public Nullable<int> PredmetC { get; set; }
        public Nullable<int> PredmetD { get; set; }
        public Nullable<int> PredmetE { get; set; }
        public int Id { get; set; }
    }
}
